upstream api_pool {
  server api:8080;
  server api-b:8080;
  keepalive 64;
}

server {
  listen 80;
  server_name _;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header ${API_EDGE_AUTH_HEADER} "${API_EDGE_AUTH_SECRET}";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";
    proxy_pass http://api_pool;
  }
}
