apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting-platform-prod

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3

  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          memory: "1Gi"
          cpu: "1000m"

images:
  - name: ghcr.io/laager-project/voting-platform-api
    newTag: latest
  - name: ghcr.io/laager-project/voting-platform-projector
    newTag: latest
  - name: ghcr.io/laager-project/voting-platform-frontend
    newTag: latest
